### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrXyfir** [cyBerta/snowflake#1]
Edit: I figured it out. Turns out something was bugged from testing and simply deleting the app and reinstalling made it work. Sorry to bother you.

---

@cyBerta forgive me for hijacking the issue tracker but I wasn't sure how else to contact you. This isn't related to this repo at all and is only indirectly related to Deltachat but if you could help me out I'd be happy to make it worth your time!

In reference to the [share extension](https://github.com/deltachat/deltachat-ios/blob/538d8a3045769c15e9ba8de3f78b98164e07bb10/DcShare/Controller/ShareViewController.swift), I have a bug in my own app that I've been unable to resolve, so I started searching Github for similar code in hopes of finding a solution.

In particular, [this line right here](https://github.com/deltachat/deltachat-ios/blob/538d8a3045769c15e9ba8de3f78b98164e07bb10/DcShare/Controller/ShareViewController.swift#L103) is where I'm having an issue. Suggestions for my app show up in the share menu of other apps, but when tapping on the suggestion to launch my share extension (which works), `self.extensionContext?.intent` is _always_ `nil`. Do you have any idea why this would be? And yes, I definitely have the `INSendMessageIntent` and related values in my `plist`.

Apple's documentation on this is awful. Going down their rabbit hole mentions adding Siri permissions and integrating an Intents extension and handler but I'm 99% sure this isn't necessary because I don't see any other apps doing that. I've compared my code to Deltachat and a few others and I don't see any obvious differences. I'm just baffled on what I'm possibly missing.

Any help would be greatly appreciated. Thanks!

**Comment by UNIFORKORU** [comment]
Great

**Comment by abigail1010** [comment]
U

**Comment by mehrankk9** [comment]
mohammadamink530@gmail.com
